(in-package #:sql-query/tests)

(defun %compile (stmt &optional (dialect (make-ansi-dialect)))
  (multiple-value-list (compile-sql stmt :dialect dialect)))

(defun %sql (stmt &optional (dialect (make-ansi-dialect)))
  (first (%compile stmt dialect)))

(defun %params (stmt &optional (dialect (make-ansi-dialect)))
  (second (%compile stmt dialect)))

(deftest select-basic
  (let ((stmt (select (columns :id :name)
                      (from :users)
                      (where (:= :active 1))
                      (order-by :name)
                      (limit 10))))
    (ok (search "SELECT" (%sql stmt)))
    (ok (search "FROM" (%sql stmt)))
    (ok (search "WHERE" (%sql stmt)))
    (ok (search "ORDER BY" (%sql stmt)))
    (ok (search "LIMIT" (%sql stmt)))
    (ok (equal '(1 10) (%params stmt)))))

(deftest select-core-shapes
  (let* ((stmt (select (distinct)
                       (columns (label (count :*) :c)
                                (sql-case (:= :active 1) "yes" :else "no"))
                       (from :users)
                       (where (sql-and
                               (sql-between :age 18 65)
                               (exists (select (columns 1)
                                              (from :orders)
                                              (where (:= :orders.user-id :users.id))))))
                       (for-update)))
         (sql (%sql stmt)))
    (ok (search "DISTINCT" sql))
    (ok (search "count(" sql) "func count")
    (ok (search "CASE" sql))
    (ok (search "BETWEEN" sql))
    (ok (search "EXISTS" sql))
    (ok (search "FOR UPDATE" sql))))

(deftest cte-union-subquery
  (let* ((inner (select (columns :id) (from :t) (where (:= :a 1))))
         (stmt (select (columns :id)
                       (with-cte (cte :x inner))
                       (from :x)))
         (u (union inner (select (columns :id) (from :u))))
         (ins (insert-into :dest (columns :id) inner)))
    (ok (search "WITH" (%sql stmt)))
    (ok (search "UNION" (%sql u)))
    (ok (search "INSERT INTO" (%sql ins)))
    (ok (search "SELECT" (%sql ins)))))

(deftest select-join-group
  (let ((stmt (select (columns :users.id (sql-fragment "count(*) AS c"))
                      (from :users)
                      (left-join :orders (on (:= :orders.user-id :users.id)))
                      (group-by :users.id)
                      (having (:> (sql-fragment "count(*)") 1)))))
    (ok (search "LEFT JOIN" (%sql stmt)))
    (ok (search "GROUP BY" (%sql stmt)))
    (ok (search "HAVING" (%sql stmt)))
    (ok (equal '(1) (%params stmt)))))

(deftest insert-update-delete
  (let ((ins (insert-into :users
               (columns :name :email)
               (sql-values "ada" "ada@example.com")))
        (upd (update :users
               (sql-set (:= :name "grace"))
               (where (:= :id 1))))
        (del (delete-from :users (where (:= :id 1)))))
    (ok (search "INSERT INTO" (%sql ins)))
    (ok (equal '("ada" "ada@example.com") (%params ins)))
    (ok (search "UPDATE" (%sql upd)))
    (ok (equal '("grace" 1) (%params upd)))
    (ok (search "DELETE FROM" (%sql del)))
    (ok (equal '(1) (%params del)))))

(deftest ddl-ansi
  (let* ((d (make-ansi-dialect))
         (ct (create-table :users
                (column :id :type :integer :primary-key t :autoincrement t)
                (column :name :type '(:varchar 255) :not-null t)
                (column :email :type :text :unique t)))
         (ci (create-index :users-email (on :users) (columns :email)))
         (at (alter-table :users (add-column :bio :type :text)))
         (dt (drop-table :users :if-exists t))
         (sql (%sql ct d)))
    (ok (search "CREATE TABLE" sql))
    (ok (search "GENERATED BY DEFAULT AS IDENTITY" sql))
    (ok (search "CHARACTER VARYING(255)" sql))
    (ok (search "CREATE INDEX" (%sql ci d)))
    (ok (search "ALTER TABLE" (%sql at d)))
    (ok (search "DROP TABLE IF EXISTS" (%sql dt d)))))

(deftest schema-table-lite
  (let* ((tbl (make-sql-table :users
                              (table-column :id :type :integer :primary-key t)
                              (table-column :name :type :text)))
         (sql (%sql (create-table-from tbl))))
    (ok (search "CREATE TABLE" sql))
    (ok (search "name" sql))))

(deftest cast-bindparam-arith
  (let ((stmt (select (columns (sql-cast :n :integer)
                               (:+ :a (bindparam :x 3)))
                      (from :t))))
    (ok (search "CAST(" (%sql stmt)))
    (ok (search "+" (%sql stmt)))
    (ok (equal '(3) (%params stmt)))))

(deftest sql-fragment-nesting
  (let ((stmt (select (columns (sql-fragment "count(*) AS c"))
                      (from :users)
                      (where (sql-and
                              (:= :tenant-id 7)
                              (sql-fragment "created_at > ?" "2020-01-01"))))))
    (ok (search "count(*) AS c" (%sql stmt)))
    (ok (equal '(7 "2020-01-01") (%params stmt)))))

(deftest parse-expr-list-form
  (let ((stmt (select (columns :id)
                      (from :t)
                      (where (parse-expr `(:and (:= :a 1) (:= :b 2)))))))
    (ok (search "AND" (%sql stmt)))
    (ok (equal '(1 2) (%params stmt)))))

(deftest compose-and-where
  (let* ((base (select (columns :id) (from :t) (where (:= :a 1))))
         (more (and-where base (:= :b 2)))
         (merged (merge-query base (limit 5))))
    (ok (equal '(1 2) (%params more)))
    (ok (search "LIMIT" (%sql merged)))
    (ok (equal '(1 5) (%params merged)))
    (ok (equal '(1) (%params base)))))

(deftest procedure-ansi-unsupported
  (let ((stmt (create-procedure :bump
                 (params (in :by :integer))
                 (body (sql-fragment "UPDATE counters SET n = n + ?" 1)))))
    (ok (signals (compile-sql stmt :dialect (make-ansi-dialect))
                 'sql-dialect-unsupported))))
