(in-package #:sql-query)

(defclass postgres-dialect (sql-dialect) ())

(defun make-postgres-dialect ()
  (make-instance 'postgres-dialect))

(defmethod dialect-param-style ((dialect postgres-dialect)) :dollar)

(defmethod dialect-type-sql ((dialect postgres-dialect) type-spec)
  (cond
    ((null type-spec) "TEXT")
    ((stringp type-spec) type-spec)
    ((keywordp type-spec)
     (case type-spec
       ((:integer :int) "INTEGER")
       ((:bigint) "BIGINT")
       ((:text :string) "TEXT")
       ((:boolean :bool) "BOOLEAN")
       ((:real :float) "REAL")
       ((:double) "DOUBLE PRECISION")
       ((:blob :bytea) "BYTEA")
       ((:timestamp) "TIMESTAMP")
       ((:timestamptz) "TIMESTAMPTZ")
       ((:date) "DATE")
       ((:serial) "SERIAL")
       (otherwise (call-next-method))))
    ((and (consp type-spec) (eq (first type-spec) :varchar))
     (format nil "VARCHAR(~a)" (second type-spec)))
    (t (call-next-method))))

(defmethod dialect-autoincrement-pk ((dialect postgres-dialect))
  "SERIAL PRIMARY KEY")

(defmethod dialect-autoincrement-suffix ((dialect postgres-dialect))
  "")

(defmethod emit-column-def ((dialect postgres-dialect) col stream ctx)
  (emit-ident dialect (column-def-name col) stream)
  (write-char #\Space stream)
  (cond
    ((and (column-def-autoincrement col) (column-def-primary-key col))
     (write-string (dialect-autoincrement-pk dialect) stream))
    ((column-def-autoincrement col)
     (write-string "SERIAL" stream)
     (when (column-def-primary-key col) (write-string " PRIMARY KEY" stream)))
    (t
     (write-string (dialect-type-sql dialect (column-def-type col)) stream)
     (when (column-def-primary-key col) (write-string " PRIMARY KEY" stream))))
  (when (column-def-not-null col) (write-string " NOT NULL" stream))
  (when (column-def-unique col) (write-string " UNIQUE" stream))
  (when (column-def-default col)
    (write-string " DEFAULT " stream)
    (let ((d (column-def-default col)))
      (emit-sql dialect (if (typep d 'sql-node) d (lit d)) stream ctx))))

(defmethod emit-create-procedure ((dialect postgres-dialect) stmt stream ctx)
  (write-string "CREATE " stream)
  (when (create-procedure-or-replace stmt)
    (write-string "OR REPLACE " stream))
  (write-string "PROCEDURE " stream)
  (emit-ident dialect (create-procedure-name stmt) stream)
  (write-char #\( stream)
  (loop for (p . rest) on (create-procedure-params stmt)
        do (write-string (ecase (procedure-param-mode p)
                           (:in "IN ")
                           (:out "OUT ")
                           (:inout "INOUT "))
                         stream)
           (emit-ident dialect (procedure-param-name p) stream)
           (write-char #\Space stream)
           (write-string (dialect-type-sql dialect (procedure-param-type p)) stream)
           (when rest (write-string ", " stream)))
  (write-string ") LANGUAGE " stream)
  (write-string (ident-string (create-procedure-language stmt)) stream)
  (write-string " AS $$" stream)
  (dolist (form (create-procedure-body stmt))
    (emit-sql dialect form stream ctx)
    (write-char #\; stream))
  (write-string "$$" stream))

(defmethod emit-call ((dialect postgres-dialect) stmt stream ctx)
  (write-string "CALL " stream)
  (emit-ident dialect (call-name stmt) stream)
  (write-char #\( stream)
  (loop for (arg . rest) on (call-args stmt)
        do (cond
             ((typep arg 'binary-op)
              ;; named: ignore name for CALL positional wave-1
              (emit-sql dialect (binary-op-right arg) stream ctx))
             (t (emit-sql dialect (ensure-expr arg) stream ctx)))
           (when rest (write-string ", " stream)))
  (write-char #\) stream))
